/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.semaozgen.DSG;

import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author sozgen
 */
public class levels2 extends javax.swing.JFrame {


    private cellNode head;
    private cellNode current;
    private int score = 0;
    private String username;
    java.awt.Color currentColor = java.awt.Color.WHITE;

    /**
     * Creates new form levels2
     */
    public levels2(String username) {
        initComponents();
        this.username = username;

        JButton[] buttons = {
            jButton1, jButton2, jButton3, jButton4, jButton5,
            jButton6, jButton7, jButton8, jButton9, jButton10,
            jButton11, jButton12, jButton13, jButton14, jButton15,
            jButton16, jButton17, jButton18, jButton19, jButton20,
            jButton21, jButton22, jButton23, jButton24, jButton25,
            jButton26, jButton27, jButton28, jButton29, jButton30
        };
        // 2 farklı trap indexi seç
        Random random = new Random();
        int trap1 = random.nextInt(30);
        int trap2;
        do {
            trap2 = random.nextInt(30);
        } while (trap2 == trap1);

        // Diğer tipler
        String[] otherTypes = {"treasure", "empty", "moveforward", "movebackward", "grandtreasure", "death"};

head = null;
cellNode prev = null;

for (int i = 0; i < 30; i++) {
    String cellType;
    if (i == trap1 || i == trap2) {
        cellType = "trap";
    } else {
        cellType = otherTypes[random.nextInt(otherTypes.length)];
    }
    cellNode node = new cellNode(buttons[i], cellType);

    // Renk ata (senin kodunla aynı)
    if (cellType.equals("treasure")) {
        node.button.setBackground(java.awt.Color.YELLOW);
    } else if (cellType.equals("trap")) {
        node.button.setBackground(java.awt.Color.RED);
    } else if (cellType.equals("moveforward")) {
        node.button.setBackground(java.awt.Color.CYAN);
    } else if (cellType.equals("movebackward")) {
        node.button.setBackground(java.awt.Color.MAGENTA);
    } else if (cellType.equals("grandtreasure")) {
        node.button.setBackground(java.awt.Color.ORANGE);
    } else if (cellType.equals("death")) {
        node.button.setBackground(java.awt.Color.BLACK);
        node.button.setForeground(java.awt.Color.WHITE);
    } else {
        node.button.setBackground(java.awt.Color.LIGHT_GRAY);
    }

    if (head == null) {
        head = node;
    }
    if (prev != null) {
        prev.next = node;
        node.prev = prev; // <-- Çift yönlü bağlantı burada!
    }
    prev = node;
}
current = head;
current.button.setBackground(currentColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_zarDurumu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_dice = new javax.swing.JButton();
        lbl_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 107, 211));
        jPanel1.setLayout(null);
        jPanel1.add(jButton1);
        jButton1.setBounds(990, 600, 72, 10);
        jPanel1.add(jButton2);
        jButton2.setBounds(1070, 630, 72, 6);
        jPanel1.add(jButton3);
        jButton3.setBounds(1170, 620, 72, 6);
        jPanel1.add(jButton4);
        jButton4.setBounds(1140, 550, 72, 6);
        jPanel1.add(jButton5);
        jButton5.setBounds(1060, 490, 72, 6);
        jPanel1.add(jButton6);
        jButton6.setBounds(980, 430, 72, 6);

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(890, 400, 72, 6);
        jPanel1.add(jButton8);
        jButton8.setBounds(800, 380, 72, 6);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(690, 380, 72, 6);
        jPanel1.add(jButton10);
        jButton10.setBounds(590, 400, 72, 6);
        jPanel1.add(jButton11);
        jButton11.setBounds(490, 410, 72, 6);
        jPanel1.add(jButton12);
        jButton12.setBounds(410, 370, 72, 6);
        jPanel1.add(jButton13);
        jButton13.setBounds(320, 320, 72, 6);
        jPanel1.add(jButton14);
        jButton14.setBounds(240, 270, 72, 6);
        jPanel1.add(jButton15);
        jButton15.setBounds(140, 250, 72, 6);
        jPanel1.add(jButton16);
        jButton16.setBounds(70, 170, 72, 6);
        jPanel1.add(jButton17);
        jButton17.setBounds(120, 80, 72, 6);
        jPanel1.add(jButton18);
        jButton18.setBounds(220, 70, 72, 6);
        jPanel1.add(jButton19);
        jButton19.setBounds(310, 110, 72, 6);
        jPanel1.add(jButton20);
        jButton20.setBounds(360, 170, 72, 6);
        jPanel1.add(jButton21);
        jButton21.setBounds(450, 220, 72, 6);
        jPanel1.add(jButton22);
        jButton22.setBounds(530, 240, 72, 6);

        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(620, 220, 72, 6);
        jPanel1.add(jButton24);
        jButton24.setBounds(710, 160, 72, 6);

        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);
        jButton25.setBounds(790, 140, 72, 6);
        jPanel1.add(jButton26);
        jButton26.setBounds(880, 160, 72, 6);
        jPanel1.add(jButton27);
        jButton27.setBounds(950, 220, 72, 6);

        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28);
        jButton28.setBounds(1030, 270, 72, 6);
        jPanel1.add(jButton29);
        jButton29.setBounds(1110, 290, 72, 6);
        jPanel1.add(jButton30);
        jButton30.setBounds(1220, 290, 72, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/sozgen/Resimler/Ekran Görüntüleri/Ekran Görüntüsü - 2025-05-03 18-40-15.png")); // NOI18N
        jLabel1.setText(".");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 640);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel2.setText("Zar Durumu :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 670, 160, 60);

        lbl_zarDurumu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_zarDurumu);
        lbl_zarDurumu.setBounds(500, 670, 260, 60);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel3.setText("Score:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(850, 660, 90, 70);

        btn_dice.setIcon(new javax.swing.ImageIcon("/home/sozgen/Masaüstü/200w.gif")); // NOI18N
        btn_dice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diceActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dice);
        btn_dice.setBounds(40, 650, 180, 110);

        lbl_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_score);
        lbl_score.setBounds(940, 670, 280, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_diceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diceActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        int dice = random.nextInt(6) + 1;
        lbl_zarDurumu.setText("Zar sonucu: " + dice);

        // LinkedList'te ilerle
        for (int i = 0; i < dice && current.next != null; i++) {
            current = current.next;
        }

        // Hücre tipine göre işlem yap
        switch (current.cellType) {
            case "treasure":
                score += 10;
                JOptionPane.showMessageDialog(this, "Hazine! +10 puan");
                break;
            case "trap":
                score -= 5;
                JOptionPane.showMessageDialog(this, "Tuzak! -5 puan");
                break;
            case "moveforward":
                JOptionPane.showMessageDialog(this, "İleri git! 2 hücre ilerliyorsun.");
                for (int i = 0; i < 2 && current.next != null; i++) {
                    current = current.next;
                }
                break;
            case "movebackward":
    JOptionPane.showMessageDialog(this, "Geri git! 2 hücre geri gidiyorsun.");
    for (int i = 0; i < 2 && current.prev != null; i++) {
        current = current.prev;
    }
    break;
            case "grandtreasure":
                score += 50;
                JOptionPane.showMessageDialog(this, "Büyük Hazine! +50 puan");
                break;
            case "death":
                JOptionPane.showMessageDialog(this, "Ölüm hücresi! Oyun bitti.");
                // Skoru kaydetmek istersen:
                FileManager.saveScore(username, "level2", score);
                this.dispose();
                return;
            default:
                JOptionPane.showMessageDialog(this, "Boş hücre. Puan yok.");
        }

        // Yeni konumu vurgula
        current.button.setBackground(java.awt.Color.GREEN);
        lbl_score.setText("Puan: " + score);

        // Oyun bitti mi?
        if (current.next == null) {
            JOptionPane.showMessageDialog(this, "Level 2 bitti! Toplam puan: " + score);
            FileManager.saveScore(username, "level2", score);
            this.dispose();
        }
    }//GEN-LAST:event_btn_diceActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_zarDurumu;
    // End of variables declaration//GEN-END:variables
}
