/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.semaozgen.DSG;

import javax.swing.*;
import java.util.Random;

/**
 *
 * @author sozgen
 */
public class levels extends javax.swing.JFrame {

    private cellNode head;
    private cellNode current;
    private int score = 0;
    private String username;

    /**
     * Creates new form levels
     */
    public levels(String username) {
        initComponents();
        this.username = username; // Kullanıcı adını kaydet
        Random random = new Random();
        int trap1 = random.nextInt(30);
        int trap2;
        do {
            trap2 = random.nextInt(30);
        } while (trap2 == trap1);

        String[] otherTypes = {"treasure", "empty"};
        cellNode prev = null;
        head = null;
        // 30 butonun her biri için bir node oluştur
        JButton[] buttons = {
            jButton2, jButton3, jButton4, jButton5,
            jButton6, jButton7, jButton8, jButton9, jButton10,
            jButton11, jButton12, jButton13, jButton14, jButton15,
            jButton16, jButton17, jButton18, jButton19, jButton20,
            jButton21, jButton22, jButton23, jButton24, jButton25,
            jButton26, jButton27, jButton28, jButton29, jButton30
        }; // Tüm butonları sırayla ekle

        for (int i = 0; i < 29; i++) {
            String cellType;
            if (i == trap1 || i == trap2) {
                cellType = "trap";
            } else {
                cellType = otherTypes[random.nextInt(otherTypes.length)];
            }
            cellNode node = new cellNode(buttons[i], cellType);
            // Renk ata
            if (cellType.equals("treasure")) {
                node.button.setBackground(java.awt.Color.YELLOW);
            } else if (cellType.equals("trap")) {
                node.button.setBackground(java.awt.Color.RED);
            } else {
                node.button.setBackground(java.awt.Color.LIGHT_GRAY);
            }

            if (head == null) {
                head = node;
            }
            if (prev != null) {
                prev.next = node;
            }
            prev = node;
        }
        current = head;
        current.button.setBackground(java.awt.Color.GREEN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        btn_rollDice = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_zarDurumu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_score = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(232, 223, 157));
        jPanel2.setLayout(null);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(490, 620, 80, 10);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LEVEL 1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(500, 40, 430, 60);

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jPanel2.add(jButton2);
        jButton2.setBounds(390, 630, 90, 10);
        jPanel2.add(jButton4);
        jButton4.setBounds(600, 610, 72, 10);

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(700, 620, 72, 6);
        jPanel2.add(jButton6);
        jButton6.setBounds(800, 620, 72, 6);
        jPanel2.add(jButton7);
        jButton7.setBounds(910, 640, 72, 6);
        jPanel2.add(jButton8);
        jButton8.setBounds(1000, 620, 72, 6);
        jPanel2.add(jButton9);
        jButton9.setBounds(1090, 580, 72, 6);
        jPanel2.add(jButton10);
        jButton10.setBounds(1150, 520, 72, 6);
        jPanel2.add(jButton11);
        jButton11.setBounds(1100, 430, 72, 6);
        jPanel2.add(jButton12);
        jButton12.setBounds(1010, 410, 72, 6);
        jPanel2.add(jButton13);
        jButton13.setBounds(910, 400, 72, 6);
        jPanel2.add(jButton14);
        jButton14.setBounds(810, 410, 72, 6);
        jPanel2.add(jButton15);
        jButton15.setBounds(710, 390, 72, 6);
        jPanel2.add(jButton16);
        jButton16.setBounds(620, 390, 72, 6);
        jPanel2.add(jButton17);
        jButton17.setBounds(520, 420, 72, 6);
        jPanel2.add(jButton18);
        jButton18.setBounds(430, 430, 72, 6);
        jPanel2.add(jButton19);
        jButton19.setBounds(340, 460, 72, 6);
        jPanel2.add(jButton20);
        jButton20.setBounds(240, 430, 72, 6);
        jPanel2.add(jButton21);
        jButton21.setBounds(170, 380, 72, 6);
        jPanel2.add(jButton22);
        jButton22.setBounds(140, 290, 72, 6);

        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton23);
        jButton23.setBounds(200, 210, 72, 10);
        jPanel2.add(jButton24);
        jButton24.setBounds(300, 220, 72, 6);
        jPanel2.add(jButton25);
        jButton25.setBounds(390, 210, 72, 6);
        jPanel2.add(jButton26);
        jButton26.setBounds(500, 220, 72, 6);
        jPanel2.add(jButton27);
        jButton27.setBounds(600, 240, 72, 6);
        jPanel2.add(jButton28);
        jButton28.setBounds(710, 230, 72, 6);
        jPanel2.add(jButton29);
        jButton29.setBounds(800, 210, 72, 6);
        jPanel2.add(jButton30);
        jButton30.setBounds(900, 210, 72, 6);

        btn_rollDice.setIcon(new javax.swing.ImageIcon("/home/sozgen/Masaüstü/200w.gif")); // NOI18N
        btn_rollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rollDiceActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rollDice);
        btn_rollDice.setBounds(20, 670, 190, 120);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel3.setText("DICE :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 700, 80, 60);

        lbl_zarDurumu.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        lbl_zarDurumu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lbl_zarDurumu);
        lbl_zarDurumu.setBounds(350, 700, 290, 70);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel5.setText("SCORE :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(780, 700, 110, 60);

        lbl_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lbl_score);
        lbl_score.setBounds(890, 700, 300, 70);
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 620, 72, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/sozgen/Resimler/Ekran Görüntüleri/Ekran Görüntüsü - 2025-05-03 01-58-15.png")); // NOI18N
        jLabel2.setText(".");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 110, 1420, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    

    
    private void btn_rollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rollDiceActionPerformed
        // TODO add your handling code here:
// Eski konumun rengini geri döndür
        if (current.cellType.equals("treasure")) {
            current.button.setBackground(java.awt.Color.YELLOW);
        } else if (current.cellType.equals("trap")) {
            current.button.setBackground(java.awt.Color.RED);
        } else {
            current.button.setBackground(java.awt.Color.LIGHT_GRAY);
        }

        // Zar at
        Random random = new Random();
        int dice = random.nextInt(6) + 1;
        lbl_zarDurumu.setText("Zar sonucu: " + dice);

        // LinkedList'te ilerle
        for (int i = 0; i < dice && current.next != null; i++) {
            current = current.next;
        }

        // Hücre tipine göre puan güncelle
        if (current.cellType.equals("treasure")) {
            score += 10;
            JOptionPane.showMessageDialog(this, "Hazine! +10 puan");
        } else if (current.cellType.equals("trap")) {
            score -= 5;
            JOptionPane.showMessageDialog(this, "Tuzak! -5 puan");
        } else {
            JOptionPane.showMessageDialog(this, "Boş hücre. Puan yok.");
        }

        // Yeni konumu vurgula
        current.button.setBackground(java.awt.Color.GREEN);
        lbl_score.setText("Puan: " + score);

        // Oyun bitti mi?
        if (current.next == null) {
            JOptionPane.showMessageDialog(this, "Oyun bitti! Toplam puan: " + score);
            // Skoru kaydetmek istersen:
            FileManager.saveScore(username, "level1", score);
            // Level2'ye geçmek istersen:
            new levels2(username).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_rollDiceActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_rollDice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_zarDurumu;
    // End of variables declaration//GEN-END:variables
}
